---
apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: frontend
 namespace: roboshop
 labels:   
   project: roboshop
   component: frontend
   tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: backend
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        project: roboshop
        component: frontend
        tier: backend
    spec:

      containers:
       - name: frontend
         image: bharathipotla/frontend:v1
         imagePullPolicy: Always
         readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 20
            periodSeconds: 50
         livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 20
          periodSeconds: 50


---
apiVersion: v1
kind: Service
metadata:
 name: frontend-service
 namespace: roboshop
spec:
 type: LoadBalancer
 selector:
   project: roboshop
   component: frontend
   tier: backend
   
 ports:
   - protocol: TCP
     port: 80 ##service port
     targetPort: 80 ##This is container port