apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: cart
 namespace: roboshop
 labels: 
  name: cart
  project: roboshop
  tier: backend
  componet: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: cart-dev
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        tier: cart-dev
    spec:
      containers:
       - name: cart
         image: bharathipotla/cart:v1
         imagePullPolicy: Always
         envFrom:
          - configMapRef:
              name: cart
         readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 20
            periodSeconds: 50
         livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 50

---
apiVersion: v1
kind: Service
metadata:
 name: cart
 namespace: roboshop
spec:
 selector:
   project: roboshop
   component: cart
   tier: backend
 ports:
   - protocol: TCP
     port: 8080 ##service port
     targetPort: 8080 ##This is container port