apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: shipping
 namespace: roboshop
 labels: 
  name: shipping
  project: roboshop
  environment: dev
  component: shipping
  tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: shipping-dev
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        tier: shipping-dev
    spec:
      containers:
       - name: shipping
         image: bharathipotla/shipping:v1
         readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 20
            periodSeconds: 50
         livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 50

---
apiVersion: v1
kind: Service
metadata:
 name: shipping-service
 namespace: roboshop
spec:
 selector:
    project: roboshop
    component: shipping
    tier: backend
 ports:
   - protocol: TCP
     port: 8080 ##service port
     targetPort: 8080 ##This is container port