apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: rabbitmq
 namespace: roboshop
 labels: 
  name: rabbitmq
  project: roboshop
  tier: db
  componet: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: rabbitmq-dev
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        tier: rabbitmq-dev
    spec:
      containers:
       - name: rabbitmq
         imagePullPolicy: Always
         image: rabbitmq:3
         env:
          - name: RABBITMQ_DEFAULT_USER
            value: roboshop
          - name: RABBITMQ_DEFAULT_PASS
            value: roboshop123 
         readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
         livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 5

---
kind: Service
metadata:
 name: rabbitmq-service
 namespace: roboshop
spec:
 selector:
   project: roboshop
   tier: db
   component: rabbitmq
   
 ports:
   - protocol: TCP
     port: 5672 ##service port
     targetPort: 5672 ##This is container port