apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: mongodb
 namespace: roboshop
 labels: 
  project: roboshop
  tier: db
  componet: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      componet: mongodb
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        project: roboshop
        tier: db
        componet: mongodb
    spec:
      containers:
       - name: mongodb
         imagePullPolicy: Always
         image: bharathipotla/mongodb:v1
         readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
         livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata: 
 name: mongodb
 namespace: roboshop
spec:
 selector:
   project: roboshop
   component: mongodb
   tier: db
 ports:
   - protocol: TCP
     port: 27017 ##service port
     targetPort: 27017 ##This is container port