apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: catalogue
 namespace: roboshop
 labels: 
  name: catalogue
  project: roboshop
  tier: backend
  componet: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: catalogue-dev
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        tier: catalogue-dev
    spec:
      containers:
       - name: catalogue
         image: bharathipotla/catalogue:v1
         imagePullPolicy: Always
         envFrom:
          - configMapRef:
              name: catalogue
         readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 20
            periodSeconds: 50
         livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 50

---
kind: Service
metadata:
 name: catalogue-service
 namespace: roboshop
spec:
 selector:
   project: roboshop
   component: catalogue
   tier: backend
   
 ports:
   - protocol: TCP
     port: 8080 ##service port
     targetPort: 8080 ##This is container port