apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: redis
 namespace: roboshop
 labels: 
  name: redis
  project: roboshop
  tier: db
  componet: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: db
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
       - name: redis
         imagePullPolicy: Always
         image: redis:7.0
         readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
         livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
 name: redis
 namespace: roboshop
spec:
 selector:
   project: roboshop
   component: redis
   tier: db
   
 ports:
   - protocol: TCP
     port: 6379 ##service port
     targetPort: 6379 ##This is container port